services:
  postgres:
    image: 'postgres:11'
    restart: always
    container_name: 'AvaliationPostgres'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
